# vim: set ts=2 sts=2 sw=2 et:
# Last change: 2025.12.20

[mgr]
# syntect_theme = "~/.config/yazi/Dracula.tmTheme"
border_style = { fg = "magenta" }

[confirm]
border = { fg = "magenta", bold = true }

[spot]
border = { fg = "magenta", bold = true }
tbl_col = { fg = "cyan" }

[input]
# This is the run shell and search box
border = { fg = "magenta", bold = true }

[filetype]
rules = [
  # Directories
  { url = "*/", fg = "cyan", bg = "blue", bold = true },
  
  # Special file types
  { url = "*", is = "orphan", fg = "red", bg = "black", bold = true, crossed = true, blink = true },
  { url = "*", is = "link", fg = "cyan", bold = true },
  { url = "*", is = "fifo", fg = "yellow", bg = "black" },
  { url = "*", is = "sock", fg = "magenta", bold = true },
  { url = "*", is = "block", fg = "yellow", bg = "black", bold = true },
  { url = "*", is = "char", fg = "yellow", bg = "black", bold = true },
  { url = "*", is = "sticky", fg = "gray", bg = "blue" },
  { url = "*", is = "exec", fg = "green", bold = true },
  
  # Archives
  { mime = "application/{gzip,x-gzip,x-tar,x-compressed-tar}", fg = "red", bold = true },
  { mime = "application/{zip,x-zip,x-zip-compressed}", fg = "red", bold = true },
  { mime = "application/{x-rar,x-rar-compressed,vnd.rar}", fg = "red", bold = true },
  { mime = "application/{x-7z-compressed,x-xz,x-bzip2}", fg = "red", bold = true },
  { mime = "application/x-compress", fg = "red", bold = true },
  { url = "*.tar", fg = "red", bold = true },
  { url = "*.tgz", fg = "red", bold = true },
  { url = "*.arc", fg = "red", bold = true },
  { url = "*.arj", fg = "red", bold = true },
  { url = "*.taz", fg = "red", bold = true },
  { url = "*.lha", fg = "red", bold = true },
  { url = "*.lz4", fg = "red", bold = true },
  { url = "*.lzh", fg = "red", bold = true },
  { url = "*.lzma", fg = "red", bold = true },
  { url = "*.tlz", fg = "red", bold = true },
  { url = "*.txz", fg = "red", bold = true },
  { url = "*.tzo", fg = "red", bold = true },
  { url = "*.t7z", fg = "red", bold = true },
  { url = "*.zip", fg = "red", bold = true },
  { url = "*.z", fg = "red", bold = true },
  { url = "*.dz", fg = "red", bold = true },
  { url = "*.gz", fg = "red", bold = true },
  { url = "*.lrz", fg = "red", bold = true },
  { url = "*.lz", fg = "red", bold = true },
  { url = "*.lzo", fg = "red", bold = true },
  { url = "*.xz", fg = "red", bold = true },
  { url = "*.zst", fg = "red", bold = true },
  { url = "*.tzst", fg = "red", bold = true },
  { url = "*.bz2", fg = "red", bold = true },
  { url = "*.bz", fg = "red", bold = true },
  { url = "*.tbz", fg = "red", bold = true },
  { url = "*.tbz2", fg = "red", bold = true },
  { url = "*.tz", fg = "red", bold = true },
  { url = "*.deb", fg = "red", bold = true },
  { url = "*.rpm", fg = "red", bold = true },
  { url = "*.jar", fg = "red", bold = true },
  { url = "*.war", fg = "red", bold = true },
  { url = "*.ear", fg = "red", bold = true },
  { url = "*.sar", fg = "red", bold = true },
  { url = "*.rar", fg = "red", bold = true },
  { url = "*.alz", fg = "red", bold = true },
  { url = "*.ace", fg = "red", bold = true },
  { url = "*.zoo", fg = "red", bold = true },
  { url = "*.cpio", fg = "red", bold = true },
  { url = "*.7z", fg = "red", bold = true },
  { url = "*.rz", fg = "red", bold = true },
  { url = "*.cab", fg = "red", bold = true },
  { url = "*.wim", fg = "red", bold = true },
  { url = "*.swm", fg = "red", bold = true },
  { url = "*.dwm", fg = "red", bold = true },
  { url = "*.esd", fg = "red", bold = true },
  
  # Images and videos using mime types
  { mime = "image/*", fg = "magenta", bold = true },
  { mime = "video/*", fg = "magenta", bold = true },
  
  # Audio files
  { mime = "audio/*", fg = "cyan" },
  
  # Backup and temporary files
  { url = "*.bak", fg = "darkgray" },
  { url = "*.bkup", fg = "darkgray" },
  { url = "*.backup", fg = "darkgray" },
  { url = "*.old", fg = "darkgray" },
  { url = "*.orig", fg = "darkgray" },
  { url = "*.part", fg = "darkgray" },
  { url = "*.rej", fg = "darkgray" },
  { url = "*.swp", fg = "darkgray" },
  { url = "*.tmp", fg = "darkgray" },
  { url = "*.dpkg-dist", fg = "darkgray" },
  { url = "*.dpkg-old", fg = "darkgray" },
  { url = "*.ucf-dist", fg = "darkgray" },
  { url = "*.ucf-new", fg = "darkgray" },
  { url = "*.ucf-old", fg = "darkgray" },
  { url = "*.rpmnew", fg = "darkgray" },
  { url = "*.rpmorig", fg = "darkgray" },
  { url = "*.rpmsave", fg = "darkgray" },

  # Fallback
  # { url = "*", fg = "white" },
]
